config/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views
from pybo.views import base_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset_complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views, comment_views, category_views

app_name = 'pybo'

urlpatterns= [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:category_id>/', base_views.index_category, name='index_category'),
    path('<int:question_id>/<int:sort>/',
         base_views.detail, name='detail'),
    path('<int:question_id>/<int:check>/',
         base_views.detail_comment, name='detail_comment_q'),



    # question_views.py
    path('question/create/<int:category_id>/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

    # comment_views.py
    path('comment/create/<int:question_id>/',
         comment_views.comment_create_q , name='comment_create_q'),

    path('comment/create_answer/<int:answer_id>/',
         comment_views.comment_create_answer , name='comment_create_answer'),

    path('comment/modify/<int:comment_id>/',
         comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/',
         comment_views.comment_delete, name='comment_delete'),
    path('comment/vote/<int:comment_id>/',
         comment_views.comment_vote, name='comment_vote'),

    #category_views.py
    path('category/create/',
         category_views.category_create, name='category_create'),
    path('category/modify/<int:category_id>/',
         category_views.category_modify, name='category_modify'),
    path('category/delete/<int:category_id>/',
         category_views.category_delete, name='category_delete'),


]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=20,unique=True, default="자유게시판")
    type = models.CharField(max_length=20,unique=True,default="free")
    can_answer = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('pybo:index', args=[self.name])

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    views = models.IntegerField(default=0)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()
    voter = models.ManyToManyField(User, related_name='voter_answer')  # 추천인 추가

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comment')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()
    voter = models.ManyToManyField(User, related_name='voter_comment')  # 추천인 추가

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment, Category


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {'content': '답변내용', }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        # labels = {'content': '댓글내용', }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'type', 'can_answer']
        labels = {'name': '카테고리 이름', 'type': 'type', 'can_answer': '답변가능여부'}

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
def answer_create(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method ==  "POST" :
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=question.id,sort = 1), answer.id))

    else:
        form = AnswerForm()
    context = {'question':question, 'form':form}
    return render(request,'pybo/question_detail.html',context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id,sort = 1), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id = answer.question.id, sort = 1)

@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(
        resolve_url('pybo:detail', question_id=answer.question.id, sort = 1), answer.id))

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question, Answer, Comment, Category
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
import datetime

def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw','')
    question_list = Question.objects.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()

    category_list = Category.objects.all()

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'page':page, 'kw':kw,'category_list':category_list, 'cur_category':0}
    return render(request,'pybo/question_list.html',context)



def index_category(request, category_id):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw','')
    question_list = Question.objects.order_by('-create_date')
    # if kw:
    #     question_list = question_list.filter(
    #         Q(subject__icontains=kw) |  # 제목 검색
    #         Q(content__icontains=kw) |  # 내용 검색
    #         Q(answer__content__icontains=kw) |  # 답변 내용 검색
    #         Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
    #         Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
    #
    #     ).distinct()
    category_list = Category.objects.all()
    category=get_object_or_404(Category,pk=category_id)
    question_list = question_list.filter(category=category)

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'page':page, 'kw':kw,'category_list':category_list, 'cur_category':category}
    return render(request,'pybo/question_list.html',context)







def detail(request, question_id, sort):
    question =get_object_or_404(Question,pk=question_id)
    page = request.GET.get('page',1)
    answer_list_cr = Answer.objects.filter(question=question).order_by('-create_date')
    answer_list_vo = Answer.objects.filter(question=question).order_by('-voter')
    question_comment = Comment.objects.filter(question=question).order_by('create_date')



    answer_list = answer_list_cr
    if sort==2:
        answer_list=answer_list_vo

    for answer in answer_list_cr:
        answer_comments = Comment.objects.filter(answer=answer).order_by('-create_date')
    paginator = Paginator(answer_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question' : question, 'answer_list':page_obj, 'q_comment_list':question_comment,
                'page':page}
    # return render(request,'pybo/question_detail.html',context)
    return view(request, question_id, context)

def detail_comment(request, question_id, check):
    question = get_object_or_404(Question, pk=question_id)
    page = request.GET.get('page',1)

    answer_list = Answer.objects.filter(question=question).order_by('-create_date')
    question_comment = Comment.objects.filter(question=question).order_by('create_date')



    paginator = Paginator(answer_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question' : question, 'answer_list':page_obj, 'q_comment_list':question_comment,
               'a_comment_list':question_comment, 'page':page, 'check':check}
    # return render(request,'pybo/question_detail.html',context)
    return view(request, question_id, context)


def view(request,question_id, context):
    question = get_object_or_404(Question, pk = question_id)
    tomorrow = datetime.datetime.replace(datetime.datetime.now(), hour=23, minute=59, second=0)
    expires = datetime.datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S GMT")
    response = render(request, 'pybo/question_detail.html', context)

    if request.session.get('authUser') is None:
        cookie_name = 'view'
    else:
        cookie_name = f'view:{request.session["authUser"]["id"]}'
    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(question_id) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{question_id}', expires=expires)
            # board.update(hit=F('hit') + 1)
            question.views += 1
            question.save()
            return response
        # [4] hit를 check하는 쿠키가 없는 경우
    else:
        response.set_cookie(cookie_name, question_id, expires=expires)
        question.views += 1
        question.save()
        return response
    return render(request, 'pybo/question_detail.html', context)

pybo/views/category_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import CategoryForm
from ..models import Category




@login_required(login_url='common:login')  # login_url='common:login' 처럼 로그인 URL을 지정할 수 있다.
def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            return redirect('pybo:index')
    else:
        form = CategoryForm()
    context = {'form': form}
    return render(request, 'pybo/category_form.html', context)

@login_required(login_url='common:login')
def category_modify(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    if request.user != category.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:index')
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            return redirect('pybo:index')
    else:
        form = CategoryForm(instance=category)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def category_delete(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    if not request.user.is_superuser:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:index')
    category.delete()
    return redirect('pybo:index')

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question, Category


@login_required(login_url='common:login')  # login_url='common:login' 처럼 로그인 URL을 지정할 수 있다.
def question_create(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.category = category
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form, 'category' : category}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id, sort=0)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id, sort = 0)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/category_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">카테고리등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="name" class="form-label">카테고리 이름</label>
            <input type="text" class="form-control" name="name" id="name"
                   value="{{ form.name.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="type" class="form-label">type</label>
            <input type="text" class="form-control" name="type"
                      id="type" value="{{ form.type.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="can_answer" class="form-check-label">답변가능여부</label>
            <input type="checkbox" class="form-check-input" name="can_answer"
                      id="can_answer" value="True">
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <h4 class="my-3 border-bottom pb-2">카테고리 : {{category.name}}</h4>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class = 'container-fruid my-3'>
    <div style="display:inline-block; width:15%">
        <div class="mx-4">
            <!-- Sidebar  -->
            <nav id="sidebar" class="border-top border-secondary">
                <div class="list-group">
                    {% for category in category_list %}
                    <div class="list-group list-group-horizontal">
                        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light text-center" href="/pybo/{{category.id}}/">
                            {{category.name}}
                            {% if request.user.username == "admin" %}
                            <a href="{% url 'pybo:category_delete' category.id %}" class="btn btn-close  list-group-item"></a>
                            {% endif %}
                        </a>
                    </div>
                    {% endfor %}
                    {% if request.user.username == "admin" %}
                    <a href="{% url 'pybo:category_create' %}" class="btn btn-primary">카테고리 만들기</a>
                    {% endif %}
                </div>
            </nav>
        </div>

<!--float:none; margin:0 auto;-->
    </div>

    <div class="container justify-content-center" style="display:inline-block; width:75%;">
        {% if cur_category %}
        <div style="font-size:35px" class="container justify-content-center col-md-3" >{{cur_category.name}}</div>
        {% endif %}
    <table class = "table table-hover">
        <thead>
        <tr class = "text-center table-dark">
            <th>번호</th>
            <td>게시판</td>
            <th style="">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
            <th>추천</th>
            <th>조회수</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class = "text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>{{ question.category.name }}</td>
            <td class="text-start">
                <a href = "{% url  'pybo:detail' question.id 0 %}" style="display:block; width:400px; text-overflow:ellipsis; overflow:hidden; white-space:nowrap;">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td> <!-- 글쓴이 추가 -->
            <td>{{ question.create_date }}</td>
            <td>{{ question.voter.count }}</td>
            <td>{{ question.views }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>



    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
<!--            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>-->
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
<!--            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>-->
             <a class="page-link" data-page="{{ page_number }}"
                href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
<!--            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>-->
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
<!--            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>-->
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}

    </ul>
    <!-- 페이징처리 끝 -->
    <form id="searchForm" method="get" action="{% url 'index' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>


         {% if cur_category %}
    <a href="{% url 'pybo:question_create' cur_category.id %}" class="btn btn-primary row" style="float:left">질문 등록하기</a>
    {% endif %}


    <div class="input-group" style="width:30%; float:right" >
        <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>
        </div>
    </div>

    </div>

</div>

{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
const search_kw = document.getElementById("search_kw");
search_kw.addEventListener('keyup', (e)=>{
    if (e.keyCode === 13) {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
  }
});
<!--인풋창에서 엔터키로 검색-->
</script>
{% endblock %}