common/urls.py
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from pybo.views import base_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.signup, name='profile'),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset_complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),


    #path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views
from pybo.views import base_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset_complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views, comment_views, category_views

app_name = 'pybo'

urlpatterns= [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:category_id>/', base_views.index_category, name='index_category'),
    path('<int:question_id>/<int:sort>/',
         base_views.detail, name='detail'),
    path('<int:question_id>/<int:check>/',
         base_views.detail_comment, name='detail_comment_q'),



    # question_views.py
    path('question/create/<int:category_id>/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

    # comment_views.py
    path('comment/create/<int:question_id>/',
         comment_views.comment_create_q , name='comment_create_q'),

    path('comment/create_answer/<int:answer_id>/',
         comment_views.comment_create_answer , name='comment_create_answer'),

    path('comment/modify/<int:comment_id>/',
         comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/',
         comment_views.comment_delete, name='comment_delete'),
    path('comment/vote/<int:comment_id>/',
         comment_views.comment_vote, name='comment_vote'),

    #category_views.py
    path('category/create/',
         category_views.category_create, name='category_create'),
    path('category/modify/<int:category_id>/',
         category_views.category_modify, name='category_modify'),
    path('category/delete/<int:category_id>/',
         category_views.category_delete, name='category_delete'),


]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, resolve_url
from common.forms import UserForm
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordChangeView, PasswordResetCompleteView
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from django.urls import reverse_lazy
FRONT_BASE_URL = 'http://127.0.0.1:8000/common'
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


class UserPasswordResetView(PasswordResetView):
    email_template_name = "common/password_reset_email.html"
    template_name = 'common/password_reset.html'  # 템플릿을 변경하려면 이와같은 형식으로 입력
    success_url = reverse_lazy('password_reset_done')
    form_class = PasswordResetForm

    def form_valid(self, form):
        if User.objects.filter(email=self.request.POST.get("email")).exists():
            return super().form_valid(form)
        else:
            return render(self.request, 'common/password_reset_done_fail.html')



class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'common/password_reset_done.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("password_reset_complete")
    template_name = "common/password_reset_confirm.html"

    def form_valid(self, form):
        return super().form_valid(form)

class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'common/password_reset_complete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['login_url'] = resolve_url(settings.LOGIN_URL)
        return context

common/views/profile_views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, resolve_url
from common.forms import UserForm
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordChangeView, PasswordResetCompleteView
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from django.urls import reverse_lazy

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
        <a class="btn btn-primary" href="{% url 'common:password_reset' %}">비밀번호 찾기</a>
    </form>
</div>
{% endblock %}

templates/common/password_reset.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
<form method="post" action="{% url 'common:password_reset' %}" style="width:400px" >
    {% csrf_token %}
    {% include "form_errors.html" %}

    <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email">
    </div>
    <button type="submit">비밀번호 초기화</button>
</form>
</div>
{% endblock %}

templates/common/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3 text-center">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-signin">
        <h1> Password reset complete </h1>
        <p> 새 비밀번호가 설정되었습니다. <a href="{% url 'common:login'%}"> 로그인 하러가기 </a>.</p>
    </div>
</div>
{% endblock %}

templates/common/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">비밀번호 초기화</button>
  </form>
</div>
{% endblock %}

templates/common/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<h1>메일 보내기</h1>
{% endblock %}

templates/common/password_reset_done_fail.html
{% extends "base.html" %}
{% block title %}
<h1>메일 보내기 실패</h1>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}