common/urls.py
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from pybo.views import base_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.signup, name='profile'),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset_complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),


    #path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views
from pybo.views import base_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset_complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views, comment_views, category_views

app_name = 'pybo'

urlpatterns= [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:category_id>/', base_views.index_category, name='index_category'),
    path('<int:question_id>/<int:sort>/',
         base_views.detail, name='detail'),
    path('<int:question_id>/<int:check>/',
         base_views.detail_comment, name='detail_comment_q'),



    # question_views.py
    path('question/create/<int:category_id>/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

    # comment_views.py
    path('comment/create/<int:question_id>/',
         comment_views.comment_create_q , name='comment_create_q'),

    path('comment/create_answer/<int:answer_id>/',
         comment_views.comment_create_answer , name='comment_create_answer'),

    path('comment/modify/<int:comment_id>/',
         comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/',
         comment_views.comment_delete, name='comment_delete'),
    path('comment/vote/<int:comment_id>/',
         comment_views.comment_vote, name='comment_vote'),

    #category_views.py
    path('category/create/',
         category_views.category_create, name='category_create'),
    path('category/modify/<int:category_id>/',
         category_views.category_modify, name='category_modify'),
    path('category/delete/<int:category_id>/',
         category_views.category_delete, name='category_delete'),


]

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question, Answer, Comment, Category
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
import datetime

def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw','')
    question_list = Question.objects.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()

    category_list = Category.objects.all()

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'page':page, 'kw':kw,'category_list':category_list, 'cur_category':0}
    return render(request,'pybo/question_list.html',context)



def index_category(request, category_id):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw','')
    question_list = Question.objects.order_by('-create_date')
    # if kw:
    #     question_list = question_list.filter(
    #         Q(subject__icontains=kw) |  # 제목 검색
    #         Q(content__icontains=kw) |  # 내용 검색
    #         Q(answer__content__icontains=kw) |  # 답변 내용 검색
    #         Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
    #         Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
    #
    #     ).distinct()
    category_list = Category.objects.all()
    category=get_object_or_404(Category,pk=category_id)
    question_list = question_list.filter(category=category)

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'page':page, 'kw':kw,'category_list':category_list, 'cur_category':category}
    return render(request,'pybo/question_list.html',context)







def detail(request, question_id, sort):
    question =get_object_or_404(Question,pk=question_id)
    page = request.GET.get('page',1)
    answer_list_cr = Answer.objects.filter(question=question).order_by('-create_date')
    answer_list_vo = Answer.objects.filter(question=question).order_by('-voter')
    question_comment = Comment.objects.filter(question=question).order_by('create_date')



    answer_list = answer_list_cr
    if sort==2:
        answer_list=answer_list_vo

    for answer in answer_list_cr:
        answer_comments = Comment.objects.filter(answer=answer).order_by('-create_date')
    paginator = Paginator(answer_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question' : question, 'answer_list':page_obj, 'q_comment_list':question_comment,
                'page':page}
    # return render(request,'pybo/question_detail.html',context)
    return view(request, question_id, context)

def detail_comment(request, question_id, check):
    question = get_object_or_404(Question, pk=question_id)
    page = request.GET.get('page',1)

    answer_list = Answer.objects.filter(question=question).order_by('-create_date')
    question_comment = Comment.objects.filter(question=question).order_by('create_date')



    paginator = Paginator(answer_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question' : question, 'answer_list':page_obj, 'q_comment_list':question_comment,
               'a_comment_list':question_comment, 'page':page, 'check':check}
    # return render(request,'pybo/question_detail.html',context)
    return view(request, question_id, context)


def view(request,question_id, context):
    question = get_object_or_404(Question, pk = question_id)
    tomorrow = datetime.datetime.replace(datetime.datetime.now(), hour=23, minute=59, second=0)
    expires = datetime.datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S GMT")
    response = render(request, 'pybo/question_detail.html', context)

    if request.session.get('authUser') is None:
        cookie_name = 'view'
    else:
        cookie_name = f'view:{request.session["authUser"]["id"]}'
    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(question_id) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{question_id}', expires=expires)
            # board.update(hit=F('hit') + 1)
            question.views += 1
            question.save()
            return response
        # [4] hit를 check하는 쿠키가 없는 경우
    else:
        response.set_cookie(cookie_name, question_id, expires=expires)
        question.views += 1
        question.save()
        return response
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html> <!--파이참 커뮤니티 버전은 오류가 남 -->
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">
    <title>kayi00z</title>
    <link rel="shortcut icon" href="{% static 'images/puzzle.ico' %}">
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->

</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">
            <img src="/static/images/puzzle.ico" alt="" width="30" height="24" class="d-inline-block align-text-top">
            kayi00</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                 <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                <li style="float:right">
                     {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:profile' %}">프로필</a>
                    {% endif %}
                </li>

            </ul>
             {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:profile' %}">프로필</a>
            {% endif %}
        </div>
    </div>
</nav>